import json
import os

from imap_tools import MailBox

from src.models import DEFAULT_CATEGORIES

HINTS_PATH = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "data",
    "category_hints.json",
)


def load_hints(limit=30):
    """Load hints generated by scripts.analyze_expenses (empty if missing)."""
    try:
        with open(HINTS_PATH) as f:
            data = json.load(f)
    except (OSError, json.JSONDecodeError):
        return [], []
    return (
        data.get("merchant_hints", [])[:limit],
        data.get("ambiguous_merchants", [])[:limit],
    )


def build_hints_block(hints, ambiguous):
    blocks = []
    if hints:
        lines = "\n".join(f"- {h['merchant']} -> {h['category']}" for h in hints)
        blocks.append(
            "Known merchants → categories. Match the brand even if spelled "
            "differently or prefixed by a processor (N1CO*, PedidosYa*). "
            f"Strong prior:\n{lines}"
        )
    if ambiguous:
        lines = "\n".join(
            "- {} -> {}".format(
                a["merchant"],
                ", ".join(f"{c} ({n})" for c, n in a["categories"].items()),
            )
            for a in ambiguous
        )
        blocks.append(
            "Merchants that appear in several categories because the name is "
            f"shared (e.g. a gas station and a store). Decide per email:\n{lines}"
        )
    return "\n".join(blocks) + "\n" if blocks else ""


def get_expense_extraction_prompt(email_content, available_categories=None):
    """
    Returns the standard prompt used for extracting expense data from email content.
    If available_categories is provided, constrains the category to that list.
    """
    if available_categories:
        cat_list = ", ".join(available_categories)
        cat_line = f"- category (string, must be one of: {cat_list})"
    else:
        cat_list = ", ".join(DEFAULT_CATEGORIES)
        cat_line = f"- category (string, must be one of: {cat_list})"

    hints_block = build_hints_block(*load_hints())

    return f"""
    Extract expense information from the following email content.
    Return the result as a JSON object with these keys:
    - is_expense (boolean): true only for a purchase at a merchant; false for
      payments, transfers, refunds/abonos, cash advances and statements.
    - amount (float)
    - currency (string, 3-letter code)
    {cat_line}
    - merchant (string)
    - source (string, the bank or financial institution, e.g., Banco Cuscatlan)
    - account (string, the specific card or account identifier, e.g., XXXXXXXXXX9104, we just need the last 4 digits without the Xs or whatever is available)
    - description (string)
    - date (string, ISO format. If no date is mentioned in the content, use the "Date:" field provided in the metadata)

    Constraint: Use only ASCII. Replace accented letters (á->a, ñ->n) and remove other special characters from string values.

    {hints_block}
    Email content:
    {email_content}
    """


def get_budget_prompt(budget_input, days=90, cap=None):
    """Prompt asking the LLM to turn recent spend into monthly limits per category."""
    total_spent = sum(b["total"] for b in budget_input)
    lines = "\n".join(
        "- {category}: {days}-day total {total:.2f} ({share:.0%} of spend), "
        "{count} expenses, avg/month {avg_month:.2f}".format(days=days, **b)
        for b in budget_input
    )
    cap_line = ""
    if cap:
        cap_line = (
            f"\n    Hard constraint: the sum of every monthly_limit must NOT "
            f"exceed {cap:.2f}.\n    Cut discretionary categories first to make "
            "room for essentials.\n"
        )
    return f"""
    You are setting a monthly budget per spending category, based on the
    last {days} days of expenses (total spent: {total_spent:.2f}). For each
    category below, propose a sensible monthly limit, anchored on the
    average/month and rounded to a clean number. A category with no spend gets
    0. The spend share shows the biggest buckets, so prioritize those.
    {cap_line}
    Return a JSON object with a single key "budgets": an array of objects with
    keys:
    - category (string, must be one of the categories below)
    - monthly_limit (float)
    - reason (string): one short line on WHY this limit — essential vs
      discretionary, a savings goal, or a one-off. Do NOT repeat the average,
      the limit, or any percentage; those are shown next to it already. Example:
      "Discretionary; trimmed to protect essentials."

    Categories:
    {lines}
    """


def format_email_for_ai(msg):
    """
    Consolidates subject, sender, date, and cleaned body into a single string for the AI.
    """
    from bs4 import BeautifulSoup
    
    subject = msg.subject
    sender = msg.from_
    # msg.date is a datetime object in imap-tools
    date_str = msg.date.strftime("%Y-%m-%d %H:%M:%S") if hasattr(msg, 'date') and msg.date else "Unknown"
    
    # Get the raw content (prefer plain text, fallback to HTML)
    raw_content = msg.text if msg.text else msg.html
    
    if msg.html and not msg.text:
        # Clean HTML if only HTML is available
        soup = BeautifulSoup(raw_content, "html.parser")
        for script_or_style in soup(["script", "style"]):
            script_or_style.decompose()
        text = soup.get_text(separator=' ')
        lines = (line.strip() for line in text.splitlines())
        chunks = (phrase.strip() for line in lines for phrase in line.split("  "))
        body = '\n'.join(chunk for chunk in chunks if chunk)
    else:
        body = raw_content

    return f"From: {sender}\nDate: {date_str}\nSubject: {subject}\n\nContent:\n{body}"

def clean_html(html_content):
    """Use BeautifulSoup for robust HTML to text conversion."""
    from bs4 import BeautifulSoup
    if not html_content:
        return ""
    soup = BeautifulSoup(html_content, "html.parser")
    # Remove script and style elements
    for script_or_style in soup(["script", "style"]):
        script_or_style.decompose()
    # Get text and clean up whitespace
    text = soup.get_text(separator=' ')
    lines = (line.strip() for line in text.splitlines())
    chunks = (phrase.strip() for line in lines for phrase in line.split("  "))
    return '\n'.join(chunk for chunk in chunks if chunk)

def check_connections():
    """Verify all external services are reachable and env vars are present before starting."""
    print("🔍 Pre-flight checks...")
    
    # 1. Check AI Key
    api_key = os.getenv("DEEPSEEK_API_KEY")
    if not api_key:
        print("❌ DEEPSEEK_API_KEY is missing!")
        return False

    # 2. Check Search Queries
    if not os.getenv("SEARCH_QUERIES"):
        print("❌ SEARCH_QUERIES is missing in environment!")
        return False
    
    # 3. Check Email Configuration
    imap_server = os.getenv("IMAP_SERVER")
    email_user = os.getenv("EMAIL_USER")
    email_password = os.getenv("EMAIL_PASSWORD")
    
    if not all([imap_server, email_user, email_password]):
        print("❌ Email configuration (IMAP_SERVER, USER, or PASSWORD) is missing!")
        return False
    
    # 4. Check Email Connection
    try:
        with MailBox(imap_server).login(email_user, email_password) as mailbox:
            print("✅ Email connection successful.")
    except Exception as e:
        print(f"❌ Email connection failed: {e}")
        return False
    
    print("🚀 All systems green!")
    return True
